# Generated by Django 3.1.7 on 2021-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
