# Generated by Django 3.1.7 on 2021-04-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_auto_20210412_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
